name: arXiv-exp-01-check
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: arXiv_bert_model_runner
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip3 install -r requirements.txt
          python3 -m project.arXiv.exp_01 -i . -o .
          echo "## Pipe 1" > report.md
          echo "BERT model-1 pipeline validated" > report.md
          cml-send-comment report.md